apiVersion: v1
kind: Service
metadata:
  name: currency-converter
spec:
  type: NodePort
  selector:
    app: currency-converter
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
